MERGE INTO GENRES (GENRE_ID, NAME) VALUES ( 1, 'Комедия' );
MERGE INTO GENRES (GENRE_ID, NAME) VALUES ( 2, 'Драма' );
MERGE INTO GENRES (GENRE_ID, NAME) VALUES ( 3, 'Мультфильм' );
MERGE INTO GENRES (GENRE_ID, NAME) VALUES ( 4, 'Триллер' );
MERGE INTO GENRES (GENRE_ID, NAME) VALUES ( 5, 'Документальный' );
MERGE INTO GENRES (GENRE_ID, NAME) VALUES ( 6, 'Боевик' );
MERGE INTO MPA_CATEGORIES (CATEGORY_MPA_ID, NAME) VALUES ( 1, 'G' );
MERGE INTO MPA_CATEGORIES (CATEGORY_MPA_ID, NAME) VALUES ( 2, 'PG' );
MERGE INTO MPA_CATEGORIES (CATEGORY_MPA_ID, NAME) VALUES ( 3, 'PG-13' );
MERGE INTO MPA_CATEGORIES (CATEGORY_MPA_ID, NAME) VALUES ( 4, 'R' );
MERGE INTO MPA_CATEGORIES (CATEGORY_MPA_ID, NAME) VALUES ( 5, 'NC-17' );

