MERGE INTO GENRES (GENRE_ID, NAME) VALUES ( 1, 'Комедия' );
MERGE INTO GENRES (GENRE_ID, NAME) VALUES ( 2, 'Драма' );
MERGE INTO GENRES (GENRE_ID, NAME) VALUES ( 3, 'Мультфильм' );
MERGE INTO GENRES (GENRE_ID, NAME) VALUES ( 4, 'Триллер' );
MERGE INTO GENRES (GENRE_ID, NAME) VALUES ( 5, 'Документальный' );
MERGE INTO GENRES (GENRE_ID, NAME) VALUES ( 6, 'Боевик' );
MERGE INTO MPA_CATEGORIES (CATEGORY_MPA_ID, NAME) VALUES ( 1, 'G' );
MERGE INTO MPA_CATEGORIES (CATEGORY_MPA_ID, NAME) VALUES ( 2, 'PG' );
MERGE INTO MPA_CATEGORIES (CATEGORY_MPA_ID, NAME) VALUES ( 3, 'PG-13' );
MERGE INTO MPA_CATEGORIES (CATEGORY_MPA_ID, NAME) VALUES ( 4, 'R' );
MERGE INTO MPA_CATEGORIES (CATEGORY_MPA_ID, NAME) VALUES ( 5, 'NC-17' );
-- MERGE INTO FILMS (FILM_ID, NAME, RELEASE_DATE, DESCRIPTION, CATEGORY_MPA_ID, DURATION, RATE) VALUES ( 1, 'FILM 1', '1990-10-10', 'FILM 1 DESCRIPTION', 2, 120, 0 );
-- MERGE INTO FILMS (FILM_ID, NAME, RELEASE_DATE, DESCRIPTION, CATEGORY_MPA_ID, DURATION, RATE) VALUES ( 2, 'FILM 2', '1991-11-11', 'FILM 2 DESCRIPTION', 3, 100, 1 );
-- DELETE FROM FILM_GENRES;
-- INSERT INTO FILM_GENRES (FILM_ID, GENRE_ID) VALUES ( 1, 2 );
-- INSERT INTO FILM_GENRES (FILM_ID, GENRE_ID) VALUES ( 1, 6 );
-- INSERT INTO FILM_GENRES (FILM_ID, GENRE_ID) VALUES ( 2, 1 );
-- INSERT INTO FILM_GENRES (FILM_ID, GENRE_ID) VALUES ( 2, 2 );


